[build]
publish = "dist"
command = "chmod +x *.sh && npm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/:category/:chapter/*"
to = "/:category/:chapter/:splat"
status = 200

[[redirects]]
from = "/:category/:chapter"
to = "/:category/:chapter/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
